# Generated by Django 3.2.5 on 2021-07-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTipoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_item', models.CharField(max_length=100, unique=True)),
                ('valor_item', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('imagem_item', models.ImageField(blank=True, null=True, upload_to='')),
                ('tipo_nome_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.modeltipoitem', verbose_name='Tipo Item')),
            ],
        ),
    ]
