# Generated by Django 3.2.5 on 2021-07-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelLista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_lista', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ModelItemLista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('lista_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.modelitem', verbose_name='Item da Lista')),
                ('tipo_lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lista.modellista', verbose_name='Tipo da Lista')),
            ],
        ),
    ]
