# Generated by Django 3.2.5 on 2021-07-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0001_initial'),
        ('Lista', '0002_alter_modelitemlista_lista_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelitemlista',
            name='lista_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.modelitem', verbose_name='Item da Lista'),
        ),
    ]
